### ISSUE TITLE
Merge and Deploy

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/calendar-hugo#24]
- [ ] Domain erstellen, auf die nachher deployed werden soll
  - [ ] Domain in `staticman.yml` eintragen `allowedOrigins: ["localhost", "example.com"]`
  - [ ] Domain in `config.toml` eintragen `baseURL`
- [ ] Ich möchte erneut Github Pages verwenden
  * Eigenes Repo dafür erstellen oder in diesem Repo bleiben?
  * Kann man "Drafts" im Repo sehen, auf dem die generierten Seiten liegen? (siehe Profilecard-public)
  - ~~Lokale Deploy Datei und Tutorial: https://gist.github.com/AngelCrawford/06dbd50beee9f96064b8dc1d71dfa120~~
    - Die Deploy Datei funktioniert nicht mehr
  * https://dev.to/usamasubhani/setup-a-blog-with-hugo-and-github-pages-562n
- [ ] Bilder verkleinern mit Github Actions: https://css-tricks.com/optimize-images-with-a-github-action/
- [ ] Github Actions einrichten, damit ein Merge ebenfalls `hugo` als Befehl ausführt und die Seite neu baut
  - [ ] https://github.com/peaceiris/actions-hugo
  - [ ] So werden Kommentare auch direkt online gebracht => Testen
  * Nachdem das Repo erstellt wurde, die Github Actions Datei erstellen
  - [ ] Git Tag in Actions: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-create-git-tag

```bash
# Create a new orphand branch (no commit history) named gh-pages
git checkout --orphan gh-pages

# Unstage all files
git rm --cached $(git ls-files)

# Grab one file from the master branch so we can make a commit
git checkout master README.md

# Add and commit that file
git add .
git commit -am "INIT: initial commit on gh-pages branch"

# Push to remote gh-pages branch
git push origin gh-pages

# Return to master branch
git checkout master

# Remove the public folder to make room for the gh-pages subtree
rm -rf public
```

```yml
name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.12
        with:
          hugo-version: '0.74.3'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
```
