### ISSUE TITLE
Better Frontmatter for events

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/calendar-hugo#43]
Alles was zusammengehört auch zusammen schreiben!

```yaml
title: Name des Events
subtitle: Ein Subtitle zum Testen in einem Event
kind: festival #concert, party, other
state: hh #sh
allDay: true
authors: angel
summary: Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
dates:
  date: 2020-05-10T10:58:08-04:00
  startDate: 2022-11-20T10:58:08-04:00
  endDate: 2022-11-24T20:00:08-04:00
  entryTime: 2022-11-20T20:00:00
location:
  venue: Name of club
  address: Eine Straße 25, 24118 Hamburg
  showMap: false
prices:
  preSale: 15,00
  boxOffice: 20.00
informations:
  corona: 2G • Keine Maskenpflicht
  cancelled: true #false
  soldOut: true #false
links:
  facebook: https://www.facebook.com
  homepage: https://www.livingdead.de
flyer:
  img: /flyer.jpg
  copyright: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore"
resources:
  - src: "flyer.jpg"
    params:
      licence: MIT
      caption: "Fotograf Namen und Webseite"
_build:
  render: false # no permalink/single-page, we WANT THIS
  list: true # but render on the list pages
```
